# -*- coding: utf-8 -*-
"""OCR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q6TK9TZ6v5lTq-vKSm9unGwhFtZvP9dK

# Download image for recognition
"""

from google.colab.patches import cv2_imshow
from cv2 import imread, IMREAD_UNCHANGED
!curl -o sign.png https://1.bp.blogspot.com/-vFPO1RjhaYI/WMmsC-WQNiI/AAAAAAAAIkg/kgiDV3fm7VwhRd34SZVhCqQIBx7ReQgmwCLcB/s640/Car-Parking-Funny-Sign-Board.jpg
img = imread('sign.png', IMREAD_UNCHANGED)
cv2_imshow(img)

"""# Common Steps :
1. install module
2. import module
3. set image path
4. open image with pillow or opencv
5. do a bit of image processing if needed
6. use module function for text recognition

# easyocr

### easyocr generates list array of tuples that having 
1. pixel co-ordinates of rectangle of recognized text as a 4x2 list array
2. actual recognized text as a string
3. accuracy of recognized text as a float
### for each recognized text in the image

Those co-ordinates and accuracy is given for doing these type of real-time-recognition 👇
"""

from google.colab.patches import cv2_imshow
from cv2 import imread, IMREAD_UNCHANGED
!curl -o car.png https://dontrepeatyourself.org/media/number-plate-recognition.webp
img = imread('car.png', IMREAD_UNCHANGED)
cv2_imshow(img)

!pip install easyocr
from IPython.display import clear_output 
clear_output()

import easyocr
reader = easyocr.Reader(['en']) # initialize reader and define language
from IPython.display import clear_output 
clear_output()

imagePath = "sign.png"

from PIL import Image
img1=Image.open(imagePath)
result = reader.readtext(img1) 
for line in result:
    print(line[1]) # print all recognized text from image

print("#############################################################################################################")

import cv2
img2=cv2.imread(imagePath)
result = reader.readtext(img2)
for line in result:
    print(line[1]) # print all recognized text from image

"""# pytesseract"""

!sudo apt install tesseract-ocr
!pip install pytesseract
from IPython.display import clear_output 
clear_output()

import pytesseract

imagePath = "sign.png"

from PIL import Image
img1=Image.open(imagePath)
print(pytesseract.image_to_string(img1)) # output type is string

print("#############################################################################################################")

import cv2
img2=cv2.imread(imagePath)
print(pytesseract.image_to_string(img2)) # output type is string