version: '3'
services:
  flask-app:
    build: .
    ports:
      - "8080"
    networks:
      - app-network
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-app
    networks:
      - app-network

networks:
  app-network:
